import type { WikiArticle } from './types'

export const rechtArticles: WikiArticle[] = [
  {
    slug: 'grundbuch',
    term: 'Grundbuch',
    category: 'recht',
    body: 'Das Grundbuch ist das amtliche Register, in dem Eigentum und Rechte an Grundstücken verzeichnet sind. Was dort eingetragen ist, gilt — es ist die Wahrheit über eine Immobilie.\n\nEs besteht aus vier Teilen: dem Bestandsverzeichnis (Beschreibung des Grundstücks, bei Wohnungen der Miteigentumsanteil), Abteilung I (Eigentümer und Erwerbsgrund), Abteilung II (Lasten und Beschränkungen wie Wohnrecht, Nießbrauch, Erbbaurecht, Wegerechte, Vormerkungen) und Abteilung III (Grundpfandrechte wie Grundschulden und Hypotheken).\n\nAls Kaufinteressent mit berechtigtem Interesse erhältst du einen aktuellen Auszug. Regel: kein Angebot ohne Blick in alle drei Abteilungen. Besonders Abteilung II kann Überraschungen bergen, die den Wert erheblich mindern.',
    legalHint: true,
  },
  {
    slug: 'notar',
    term: 'Notar',
    category: 'recht',
    body: 'Der Notar ist beim Immobilienkauf gesetzlich zur Neutralität verpflichtet. Er beurkundet den Kaufvertrag, sorgt für die korrekte Abwicklung (Auflassungsvormerkung, Grundbucheintrag, Treuhandauflagen) und erklärt auf Nachfrage jede Klausel — seine Erklärung ist im Honorar enthalten.\n\nWichtig: Der Notar prüft nicht, ob der Preis fair oder das Objekt gut ist — das bleibt deine Aufgabe. Für einseitige Interessenvertretung, Verhandlungen oder Streit brauchst du einen Anwalt.\n\nBei Verbraucherbeteiligung soll der Vertragsentwurf mindestens 14 Tage vor dem Termin vorliegen — nutze diese Frist zum Lesen und Fragen. Erst nach der Fälligkeitsmitteilung des Notars, wenn alle Voraussetzungen erfüllt sind, zahlst du den Kaufpreis — niemals vorher und niemals am Notar vorbei.',
    legalHint: true,
  },
  {
    slug: 'kaufvertrag',
    term: 'Kaufvertrag',
    category: 'recht',
    body: 'Der notarielle Kaufvertrag ist das juristische Herzstück des Immobilienerwerbs und muss zwingend beurkundet werden. Zu den Kernklauseln zählen: Kaufgegenstand (exakt nach Grundbuch, mitverkauftes Zubehör separat ausgewiesen), Kaufpreis und Fälligkeitsvoraussetzungen, Auflassung und Vormerkung, Besitzübergang („Nutzen und Lasten"), Gewährleistung und die Belastungsvollmacht (damit deine Bank die Grundschuld eintragen kann).\n\nBei gebrauchten Immobilien wird die Sachmängelhaftung üblicherweise ausgeschlossen („gekauft wie gesehen") — Ausnahme sind arglistig verschwiegene Mängel. Deshalb ist die Prüfung vor dem Vertrag so entscheidend.\n\nBei Eigentumswohnungen gehören Regelungen zu Rücklage und beschlossenen Sonderumlagen hinein. Nie am Notar vorbei zahlen — das ist riskant bis strafbar.',
    legalHint: true,
  },
  {
    slug: 'auflassungsvormerkung',
    term: 'Auflassungsvormerkung',
    category: 'recht',
    body: 'Die Auflassungsvormerkung ist ein Eintrag in Abteilung II des Grundbuchs, der dein Anrecht auf das Eigentum sichert — in der Zeit zwischen Beurkundung des Kaufvertrags und deiner endgültigen Eintragung als Eigentümer.\n\nSie schützt dich davor, dass der Verkäufer das Objekt zwischenzeitlich ein zweites Mal verkauft, zusätzlich belastet oder dass Gläubiger des Verkäufers darauf zugreifen. Die Vormerkung wirkt über ihren Rang: Sie blockiert alle späteren Verfügungen.\n\nDie Eintragung der Vormerkung ist typischerweise eine der Voraussetzungen dafür, dass der Notar die Kaufpreiszahlung fällig stellt. Der eigentliche Eigentümerwechsel im Grundbuch folgt oft erst Wochen später — bis dahin bist du durch die Vormerkung geschützt.',
    legalHint: true,
  },
  {
    slug: 'teilungserklaerung',
    term: 'Teilungserklärung',
    category: 'recht',
    body: 'Die Teilungserklärung ist das Grunddokument jeder Eigentumswohnung — die „Verfassung" der Wohnungseigentümergemeinschaft (WEG). Sie teilt das Gebäude in Sondereigentum (was dir allein gehört, im Wesentlichen die Räume deiner Wohnung) und Gemeinschaftseigentum (Dach, Fassade, tragende Wände, Treppenhaus, meist die Fenster, Leitungsstränge).\n\nSie legt außerdem die Miteigentumsanteile fest (Grundlage für Stimmrecht und Kostenverteilung) und regelt Sondernutzungsrechte (z. B. Garten, Stellplatz). Häufig gehört eine Gemeinschaftsordnung dazu, die Sonderregeln enthalten kann — etwa Vermietungsbeschränkungen oder Nutzungsvorgaben.\n\nVor jedem ETW-Kauf gehört die Teilungserklärung samt Gemeinschaftsordnung zur Pflichtlektüre: Sie bestimmt, was dir gehört, was du zahlst und was du darfst.',
    legalHint: true,
  },
  {
    slug: 'weg',
    term: 'WEG (Wohnungseigentümergemeinschaft)',
    category: 'recht',
    body: 'Die Wohnungseigentümergemeinschaft (WEG) ist die Gemeinschaft aller Eigentümer eines Mehrparteienhauses mit Eigentumswohnungen. Wer eine ETW kauft, wird automatisch Teil der WEG und tritt damit einer Organisation bei.\n\nDie WEG verwaltet das Gemeinschaftseigentum, beschließt in der jährlichen Eigentümerversammlung über Wirtschaftsplan, Jahresabrechnung, Verwalterbestellung und Instandhaltung. Seit der WEG-Reform 2020 reicht für die meisten Beschlüsse die einfache Mehrheit der abgegebenen Stimmen — du kannst also überstimmt werden, auch bei kostspieligen Sanierungen mit Sonderumlage.\n\nDeshalb gehört die „Gesundheit" einer WEG zur Kaufprüfung: Höhe der Instandhaltungsrücklage, Protokolle der letzten Versammlungen (konstruktiv oder zerstritten?), laufende Rechtsstreitigkeiten. Zwei identische Wohnungen in Nachbarhäusern können durch ihre WEG völlig unterschiedliche Investments sein.',
    legalHint: true,
  },
  {
    slug: 'sondernutzungsrecht',
    term: 'Sondernutzungsrecht',
    category: 'recht',
    body: 'Ein Sondernutzungsrecht ist das exklusive Recht, eine bestimmte Fläche des Gemeinschaftseigentums allein zu nutzen — typischerweise ein Gartenanteil, ein Stellplatz oder ein Kellerraum. Die Fläche bleibt rechtlich Gemeinschaftseigentum, du darfst sie aber ausschließlich nutzen.\n\nWichtig beim Kauf: Was ein Exposé „Garten" oder „eigener Stellplatz" nennt, ist rechtlich oft nur ein Sondernutzungsrecht, kein Sondereigentum. Der Unterschied ist relevant: Bauliche Veränderungen an der Fläche brauchen weiterhin die Zustimmung der Gemeinschaft, und das Recht ist an die Wohnung gebunden.\n\nSondernutzungsrechte werden in der Teilungserklärung bzw. Gemeinschaftsordnung geregelt. Prüfe bei mitbeworbenen Flächen genau, ob es sich um Sondereigentum oder ein Sondernutzungsrecht handelt.',
    legalHint: true,
  },
  {
    slug: 'niessbrauch',
    term: 'Nießbrauch',
    category: 'recht',
    body: 'Der Nießbrauch ist ein in Abteilung II des Grundbuchs eingetragenes Recht, eine Sache umfassend zu nutzen und ihre Erträge zu ziehen — ohne Eigentümer zu sein. Bei einer Immobilie darf der Nießbraucher also darin wohnen oder sie vermieten und die Mieten behalten.\n\nFür einen Käufer ist ein bestehender Nießbrauch gravierend: Er kann das Objekt trotz Eigentums weder nutzen noch dessen Erträge behalten, solange das Recht besteht (oft lebenslang). Der Wert des Objekts wird dadurch erheblich gemindert.\n\nNießbrauch wird häufig bei vorweggenommener Erbfolge genutzt (Eltern übertragen die Immobilie an die Kinder, behalten aber den Nießbrauch). Beim Kauf gilt: Jedes Recht in Abteilung II muss erkannt, verstanden und eingepreist werden — im Zweifel mit Notar oder Anwalt.',
    legalHint: true,
  },
  {
    slug: 'erbbaurecht',
    term: 'Erbbaurecht',
    category: 'recht',
    body: 'Beim Erbbaurecht gehört dir das Gebäude, aber nicht der Grund und Boden. Du pachtest das Grundstück von einem Erbbaurechtsgeber (oft Kirche, Kommune oder Stiftung) für eine lange Laufzeit — meist 60 bis 99 Jahre — und zahlst dafür einen laufenden Erbbauzins.\n\nVorteil: Der Kaufpreis ist niedriger, weil der teure Boden nicht mitgekauft wird. Nachteile: der laufende Erbbauzins (der angepasst werden kann), eine schwierigere und teurere Finanzierung, eine kleinere Käuferschicht beim Wiederverkauf und besondere Regelungen am Laufzeitende (Heimfall, Entschädigung).\n\nErbbaurecht-Objekte sind nichts pauschal Schlechtes, aber sie erfordern eine sorgfältige Prüfung der Restlaufzeit und der Vertragskonditionen. Für Einsteiger sind sie eher ein Sonderfall als ein Standardkauf.',
    legalHint: true,
  },
  {
    slug: 'zwangsversteigerung',
    term: 'Zwangsversteigerung',
    category: 'recht',
    body: 'Bei einer Zwangsversteigerung wird eine Immobilie auf gerichtlichem Weg verwertet — meist weil der Eigentümer seinen Kredit nicht mehr bedienen kann und die Bank ihre Grundschuld vollstreckt. Der Zuschlag erfolgt an den Meistbietenden im Versteigerungstermin.\n\nChancen: Objekte sind manchmal unter Marktwert zu bekommen. Risiken sind aber erheblich: Es gibt keinen Kaufvertrag und kein Gewährleistungsrecht, die Besichtigung ist oft nur eingeschränkt möglich, bestehende Rechte (etwa Mietverhältnisse oder nicht erlöschende Lasten) können bestehen bleiben, und im Bieterrausch wird schnell zu viel geboten.\n\nZwangsversteigerungen erfordern hohe Expertise (Verkehrswertgutachten und Grundbuch genau lesen, Bietstrategie), Kapital und Nervenstärke — nichts für den ersten Kauf, aber eine mögliche Spezialquelle für erfahrene Investoren.',
    legalHint: true,
  },
  {
    slug: 'mietvertrag',
    term: 'Mietvertrag',
    category: 'recht',
    body: 'Der Mietvertrag regelt das Verhältnis zwischen Vermieter und Mieter über Jahre. Nutze eine aktuelle, geprüfte Vorlage (z. B. von Eigentümerverbänden) — unwirksame Klauseln fallen immer zu Lasten des Vermieters weg, dann gilt die oft mieterfreundlichere gesetzliche Regelung.\n\nKerninhalte: Parteien und Wohnung, Miethöhe (fest, gestaffelt oder indexiert), Betriebskostenumlage mit Vorauszahlung, Kaution (max. drei Nettokaltmieten), Schönheitsreparaturen (nur mit flexibler, wirksamer Klausel übertragbar) und ein Übergabeprotokoll als Anlage.\n\nWichtig: „Kauf bricht nicht Miete" — beim Erwerb eines vermieteten Objekts übernimmst du den bestehenden Vertrag mit allen Rechten und Pflichten. Typische unwirksame Klauseln (starre Renovierungsfristen, pauschale Tierhaltungsverbote) unbedingt vermeiden.',
    legalHint: true,
  },
  {
    slug: 'mieterselbstauskunft',
    term: 'Mieterselbstauskunft',
    category: 'recht',
    body: 'Die Mieterselbstauskunft ist ein Formular, mit dem ein Mietbewerber dem Vermieter Angaben zu seiner Person und finanziellen Situation macht — Einkommen, Beruf, Zahl der Bewohner, bestehende Mietverhältnisse.\n\nZulässig sind Fragen, die für die Vermietung relevant sind: Einkommensnachweise, SCHUFA-BonitätsAuskunft, ggf. eine Mietschuldenfreiheitsbescheinigung. Unzulässig sind Fragen nach Familienplanung, Religion, Herkunft, Parteizugehörigkeit oder Vorstrafen — auf solche darf der Bewerber falsch antworten, ohne Konsequenzen (Schutz durch AGG und Datenschutz).\n\nAls Faustregel für die Bezahlbarkeit sollte die Warmmiete etwa ein Drittel des Nettoeinkommens nicht übersteigen. Wichtig: Die Unterlagen abgelehnter Bewerber sind datenschutzkonform zu löschen, nicht zu sammeln.',
    legalHint: true,
  },
  {
    slug: 'kaution',
    term: 'Mietkaution',
    category: 'recht',
    body: 'Die Mietkaution ist eine Sicherheitsleistung des Mieters für mögliche Ansprüche des Vermieters am Ende des Mietverhältnisses — etwa für Schäden über normale Abnutzung hinaus, ausstehende Mieten oder Nebenkostennachzahlungen.\n\nGesetzliche Grenzen: Die Kaution darf höchstens drei Nettokaltmieten betragen, der Mieter darf sie in drei Monatsraten zahlen. Der Vermieter muss sie getrennt von seinem eigenen Vermögen und insolvenzfest anlegen (z. B. auf einem verpfändeten Kautionssparbuch) — sie bleibt Vermögen des Mieters und ist zu verzinsen.\n\nNach dem Auszug hat der Vermieter eine angemessene Frist (üblich einige Monate, insbesondere um die Betriebskostenabrechnung abzuwarten), um über die Rückzahlung zu entscheiden. Berechtigte Ansprüche darf er einbehalten, den Rest muss er auszahlen.',
    legalHint: true,
  },
  {
    slug: 'mietpreisbremse',
    term: 'Mietpreisbremse',
    category: 'recht',
    body: 'Die Mietpreisbremse begrenzt in Gebieten mit angespanntem Wohnungsmarkt die zulässige Miete bei Neuvermietung: Sie darf grundsätzlich höchstens 10 % über der ortsüblichen Vergleichsmiete liegen. Ob sie an einem Standort gilt, legen die Bundesländer per Verordnung fest.\n\nEs gibt wichtige Ausnahmen: Neubauten (erstmalige Nutzung ab einem bestimmten Stichtag), umfassend modernisierte Wohnungen und die vorherige Miete, wenn sie bereits höher war (Bestandsschutz). Der Vermieter muss über die Vormiete bzw. Ausnahmen unter Umständen Auskunft geben.\n\nFür Investoren heißt das: Bei Neuvermietung in Bremse-Gebieten die zulässige Ausgangsmiete prüfen. Die Regelung wird regelmäßig verlängert und angepasst — den aktuellen Stand für den konkreten Standort prüfen. Von der Mietpreisbremse zu unterscheiden ist die Kappungsgrenze für Erhöhungen im Bestand.',
    legalHint: true,
  },
  {
    slug: 'kappungsgrenze',
    term: 'Kappungsgrenze',
    category: 'recht',
    body: 'Die Kappungsgrenze begrenzt Mieterhöhungen im laufenden Mietverhältnis: Die Miete darf innerhalb von drei Jahren um höchstens 20 % steigen — in Gebieten mit angespanntem Wohnungsmarkt sogar nur um 15 %. Zusätzlich ist die ortsübliche Vergleichsmiete stets die Obergrenze.\n\nSie betrifft Erhöhungen bis zur Vergleichsmiete (anders als die Mietpreisbremse, die die Neuvermietungsmiete regelt, und anders als Modernisierungsumlagen, die eigenen Regeln folgen).\n\nFür Investoren praktisch bedeutsam: Eine deutlich unter Markt vermietete Wohnung ist kein schneller Gewinn. Das Mietpotenzial lässt sich nur langsam und in gesetzlichen Schritten heben. Wer mit sofortiger Anhebung auf Marktniveau kalkuliert, rechnet falsch — die Kappungsgrenze setzt dem enge Grenzen.',
    legalHint: true,
  },
  {
    slug: 'kuendigung',
    term: 'Kündigung (Mietrecht)',
    category: 'recht',
    body: 'Im Mietrecht ist der Mieter deutlich stärker geschützt als der Vermieter. Als Vermieter kannst du ein unbefristetes Wohnraummietverhältnis nur mit berechtigtem Interesse ordentlich kündigen — vor allem bei Eigenbedarf (ernsthaft, konkret, begründet) oder erheblichen Vertragsverletzungen des Mieters.\n\nEine fristlose Kündigung kommt insbesondere bei Zahlungsverzug in Betracht: bei einem Rückstand von rund zwei Monatsmieten. Sie kann der Mieter jedoch durch vollständige Nachzahlung innerhalb der Schonfrist unwirksam machen (einmal in zwei Jahren). Verhaltensbedingte Kündigungen setzen meist eine vorherige, dokumentierte Abmahnung voraus.\n\n„Einfach rauswerfen" gibt es nicht. Eigenmächtige Selbsthilfe (Schloss austauschen, Strom abstellen) ist verboten und schadensersatzpflichtig. Bei Kündigung und Räumung gehört ein Fachanwalt für Mietrecht ans Ruder.',
    legalHint: true,
  },
  {
    slug: 'mietminderung',
    term: 'Mietminderung',
    category: 'recht',
    body: 'Die Mietminderung ist das Recht des Mieters, die Miete zu kürzen, wenn ein Mangel die Gebrauchstauglichkeit der Wohnung erheblich einschränkt — etwa Heizungsausfall im Winter, Schimmel oder ein undichtes Dach. Die Minderung muss in einem angemessenen Verhältnis zur Beeinträchtigung stehen.\n\nVoraussetzung ist in der Regel, dass der Mieter den Mangel gemeldet hat und der Vermieter Gelegenheit zur Behebung hatte. Bagatellen und selbst verursachte Mängel berechtigen nicht zur Minderung.\n\nFür den Vermieter ist die beste Verteidigung, Mängel schnell zu beheben — dann entfällt die Grundlage. Unberechtigte oder überhöhte Minderungen kannst und solltest du sachlich zurückweisen und die einbehaltene Differenz einfordern. Verschleppte Reparaturen dagegen führen zu berechtigten und dauerhaften Kürzungen.',
    legalHint: true,
  },
  {
    slug: 'abmahnung',
    term: 'Abmahnung (Mietrecht)',
    category: 'recht',
    body: 'Die Abmahnung ist die formelle Rüge einer Vertragsverletzung durch den Mieter — etwa fortgesetzte Ruhestörung, unerlaubte Untervermietung oder vertragswidriger Gebrauch. Sie benennt das Fehlverhalten konkret, fordert zur Unterlassung auf und kündigt Konsequenzen (bis zur Kündigung) an.\n\nBei verhaltensbedingten Kündigungen ist eine vorherige, dokumentierte Abmahnung meist zwingende Voraussetzung: Ohne sie scheitert eine Kündigung häufig vor Gericht. Die Abmahnung gibt dem Mieter die Chance, sein Verhalten zu ändern, und schafft für den Vermieter die nötige Beweisgrundlage.\n\nWichtig ist die Dokumentation: schriftlich, mit konkreter Schilderung (wer, was, wann, wie oft) und nachweisbarem Zugang. Bei wiederholtem oder schwerem Fehlverhalten kann nach erfolgloser Abmahnung die Kündigung folgen — im Ernstfall mit anwaltlicher Begleitung.',
    legalHint: true,
  },
  {
    slug: 'raeumungsklage',
    term: 'Räumungsklage',
    category: 'recht',
    body: 'Die Räumungsklage ist der gerichtliche Weg, einen Mieter nach einer wirksamen Kündigung zum Auszug zu zwingen, wenn er die Wohnung nicht freiwillig verlässt. Sie ist der einzige legale Weg — eigenmächtige „Selbsthilfe" ist verboten und macht den Vermieter schadensersatzpflichtig.\n\nDer Ablauf ist langwierig: Nach wirksamer Kündigung folgt die Klage, ein Gerichtsverfahren, ein Räumungsurteil und schließlich die Zwangsvollstreckung durch den Gerichtsvollzieher. Das kann Monate dauern, und Gerichte gewähren Mietern teils Räumungsfristen. In dieser Zeit fließt oft keine Miete.\n\nDeshalb gilt: Eine Räumungsklage gehört in die Hände eines Fachanwalts für Mietrecht, und die beste Prävention ist eine sorgfältige Mieterauswahl zu Beginn. Die meisten Räumungsfälle lassen sich durch gute Auswahl und frühzeitige, faire Kommunikation vermeiden.',
    legalHint: true,
  },
  {
    slug: 'uebergabeprotokoll',
    term: 'Übergabeprotokoll',
    category: 'recht',
    body: 'Das Übergabeprotokoll dokumentiert den Zustand einer Wohnung und alle Zählerstände zum Zeitpunkt der Übergabe — bei Einzug wie bei Auszug. Es ist keine Formalie, sondern die wichtigste Beweisurkunde bei späteren Streitigkeiten.\n\nInhalt: Datum und Beteiligte, Zählerstände mit Zählernummern, Zustand jedes Raums (ehrlich, inklusive vorhandener Mängel und Gebrauchsspuren), Anzahl und Art der übergebenen Schlüssel, mitvermietete Ausstattung. Beide Seiten unterschreiben, jeder bekommt ein Exemplar; datierte Fotos ergänzen es sinnvoll.\n\nBeim Auszug ist das Einzugsprotokoll der Maßstab: Nur was neu und über normale Abnutzung hinausgeht, kann der Vermieter geltend machen. Ohne dokumentierten Einzugszustand steht im Streit Aussage gegen Aussage — dann verliert meist der Vermieter.',
  },
]
